### ISSUE TITLE
Require minimum stable version of dot-access-configuration

### ISSUE THREAD

**Issue by grasmash** [hechoendrupal/drupal-console-core#123] opened 2016-12-29 14:58 UTC
The composer.json file for drupal-console-core currently requires "dev-master" for `dflydev/dot-access-configuration`. This does not follow best practices for a composer package, which dictate that a minimum stable version should be defined.

Would it be possible to change this constraint?

**Comment by jmolivas** [comment] 2016-12-30 04:17
@grasmash I will ping the maintainer and ask to tag a release since latest stable is broken when using symfony 3.x components.

**Comment by jmolivas** [comment] 2016-12-30 05:25
This is my PR https://github.com/dflydev/dflydev-dot-access-configuration/pull/8 fixing the issue at the `dflydev/dot-access-configuration` project.

Releases page: https://github.com/dflydev/dflydev-dot-access-configuration/releases

**Comment by greg-1-anderson** [comment] 2017-01-10 16:46
The dev-master dependency is causing problems for me as well. Drupal Console  /Drupal Consoel Core 1.0.0-rc14, Drupal 8.2.5, symfony/console 2.8.15.

Initial symptom:
```
Fatal error: require(): Failed opening required '.../vendor/composer/../dflydev/dot-access-configuration/src/Dflydev/DotAccessConfiguration/YamlFileConfigurationBuilder.php' (include_path='.:/usr/share/pear:/usr/share/php') in .../vendor/symfony/class-loader/ApcClassLoader.php on line 110
```
Then, after `composer update` (which apparently updated nothing, just rewrote the autoload files):
```
Error: Class &#039;Dflydev\DotAccessConfiguration\YamlFileConfigurationBuilder&#039; not found in Drupal\Console\Core\Utils\ConfigurationManager->loadConfiguration() (line 86 of .../vendor/drupal/console-core/src/Utils/ConfigurationManager.php).
```
It seems that dev-master of dflydev/dot-access-configuration has drifted, and no longer works with Drupal Console 1.0.0-rc14.  Since rc14 is for Drupal 8.2.5, and Symfony 3.x is only in dev releases of Drupal (didn't check today, but last I heard even dev was back to 2.x), couldn't you require the stable tag in your rc releases, and dev-master in your dev branch? As @grasmash says, it's frustrating when the dependencies of an rc release drift over time.

**Comment by greg-1-anderson** [comment] 2017-01-10 16:53
`composer require dflydev/dot-access-configuration:1.0.1` is not a viable workaround, as that conflicts with the dev-master request in drupal/console-core.

_Wonders if there's a way to define a Composer version alias via a Composer command._

**Comment by greg-1-anderson** [comment] 2017-01-10 16:54
Like https://getcomposer.org/doc/articles/aliases.md, but for the command line.

**Comment by greg-1-anderson** [comment] 2017-01-10 16:57
`composer require 'dflydev/dot-access-configuration:1.0.1 as dev-master'` almost does the trick, except I get:

`The .git directory is missing from ...`

Might work if I get that back, though. I think I stripped it deliberately.

**Comment by greg-1-anderson** [comment] 2017-01-10 17:00
`.git` directories are another reason why requiring dev-master from an rc release is really inconvenient.

**Comment by jmolivas** [comment] 2017-01-10 17:18
looking at this @greg-1-anderson, thanks for the information

**Comment by greg-1-anderson** [comment] 2017-01-10 17:51
Confirmed that dflydev/dot-access-configuration:1.0.1 works with Drupal Console 1.0.0-rc14 and Drupal 8.2.5.

**Comment by jmolivas** [comment] 2017-01-10 17:53
Tagging an rc15 today cc: @greg-1-anderson @grasmash

**Comment by jmolivas** [comment] 2017-01-18 07:55
Fixed with https://github.com/hechoendrupal/drupal-console-core/pull/135

**Closed** 2017-01-19 07:36 UTC

**Comment by grasmash** [comment] 2017-01-20 16:14
@jmolivas What did you do about needing the `has()` method? I'm petitioning for a 1.1.0 release :)

https://github.com/dflydev/dflydev-dot-access-data/issues/5
https://twitter.com/grasmash/status/822476053256015872

**Comment by greg-1-anderson** [comment] 2017-01-20 17:48
@jmolivas We could still use an rc15 tag as well. Do you have an updated estimate on when that will be available?

**Comment by grasmash** [comment] 2017-01-23 17:19
https://github.com/dflydev/dflydev-dot-access-data/releases/tag/v1.1.0 was released!

**Comment by jmolivas** [comment] 2017-01-23 18:26
@grasmash @greg-1-anderson RC-15 tagged
